import { Solution } from "@/types";

export const categories = [
  ["AI & Machine Learning", "Models and intelligent workflows", "Brain"], ["Automation", "Remove repetitive work", "Workflow"], ["Cybersecurity", "Build with confidence", "ShieldCheck"], ["Web & Cloud", "Digital platforms at scale", "Cloud"], ["Data & Analytics", "Make data useful", "BarChart3"], ["Testing", "Quality built in", "TestTube2"], ["DevOps", "Deliver reliably", "GitBranch"], ["Embedded Systems", "Software close to hardware", "Cpu"], ["Developer Tools", "Improve engineering flow", "Code2"], ["Productivity", "Work better together", "Sparkles"], ["IoT", "Connect physical and digital", "Radio"], ["Computer Vision", "See patterns automatically", "ScanLine"]
];

export const solutions: Solution[] = [
  {id:"visual-quality-inspection",name:"Visual Quality Inspection",description:"Detects manufacturing defects from factory camera images with a repeatable review workflow.",category:"Computer Vision",type:"AI/ML",department:"Manufacturing",team:"Computer Vision Team",technologies:["Python","OpenCV","TensorFlow"],verified:true,maintained:true,reuseCount:17,contributors:4,updated:"2 days ago",availability:"Organization",keywords:["defect","camera","image","vision","manufacturing","quality","inspection","detection"],impact:"1,240 hours saved",accent:"#295b8f"},
  {id:"test-orchestrator",name:"Test Orchestrator",description:"A reusable test automation framework for orchestrating integration and regression suites.",category:"Testing",type:"Framework",department:"Engineering",team:"Quality Engineering",technologies:["Java","Docker","Azure"],verified:true,maintained:true,reuseCount:31,contributors:7,updated:"4 days ago",availability:"Organization",keywords:["test","automation","regression","integration","quality","sap"],impact:"2,100 hours saved",accent:"#3f6d60"},
  {id:"document-intelligence",name:"Document Intelligence Pipeline",description:"Extracts fields, classifies documents and routes exceptions for human review.",category:"Automation",type:"Automation",department:"Finance",team:"Intelligent Operations",technologies:["Python","Azure","AI/ML"],verified:true,maintained:true,reuseCount:22,contributors:5,updated:"1 week ago",availability:"Department",keywords:["invoice","ocr","document","processing","extraction","automation"],impact:"980 hours saved",accent:"#8a6237"},
  {id:"secure-api-gateway",name:"Secure API Gateway Blueprint",description:"A production-ready pattern for API policy, observability and internal access control.",category:"Cybersecurity",type:"Framework",department:"IT",team:"Platform Security",technologies:["Java","Azure","Docker"],verified:true,maintained:true,reuseCount:14,contributors:6,updated:"3 days ago",availability:"Organization",keywords:["api","security","gateway","authentication","policy"],impact:"730 hours saved",accent:"#5a4c78"},
  {id:"data-quality-monitor",name:"Data Quality Monitor",description:"Monitors critical data pipelines and alerts teams before quality issues spread.",category:"Data & Analytics",type:"Tool",department:"Research",team:"Data Foundations",technologies:["Python","Azure","React"],verified:false,maintained:true,reuseCount:9,contributors:3,updated:"1 week ago",availability:"Organization",keywords:["data","quality","monitoring","pipeline","analytics"],impact:"420 hours saved",accent:"#315b66"},
  {id:"edge-device-kit",name:"Edge Device Provisioning Kit",description:"Provision and update embedded devices securely across controlled environments.",category:"Embedded Systems",type:"Library",department:"Mobility",team:"Embedded Platform",technologies:["C++","Docker","IoT"],verified:true,maintained:true,reuseCount:19,contributors:8,updated:"5 days ago",availability:"Team",keywords:["embedded","device","iot","provisioning","firmware"],impact:"1,050 hours saved",accent:"#496154"}
];
const expanded = ["Cloud Cost Lens","Release Health Dashboard","Accessibility Check Kit","Supply Chain Signal API","Factory Energy Optimizer","Knowledge Graph Explorer","Container Baseline","Log Insight Toolkit","Field Service Scheduler","Identity Integration Guide","Fleet Telemetry Library","Code Review Assistant","Process Mining Starter","Web Component Library"];
expanded.forEach((name,i)=>solutions.push({id:name.toLowerCase().replace(/[^a-z0-9]+/g,"-"),name,description:`A maintained reusable ${["tool","framework","automation","library"][i%4]} for Bosch teams to accelerate delivery and collaboration.`,category:categories[i%categories.length][0],type:["Tool","Library","Automation","Software"][i%4],department:["Engineering","IT","Manufacturing","Research"][i%4],team:["Developer Productivity","Platform Team","Digital Factory","Innovation Lab"][i%4],technologies:[["React","TypeScript"],["Python","Azure"],["Docker","Java"],["C++","IoT"]][i%4],verified:i%3!==0,maintained:i%5!==0,reuseCount:3+i,contributors:2+i%5,updated:`${i+2} days ago`,availability:["Organization","Department","Team"][i%3] as Solution["availability"],keywords:name.toLowerCase().split(" "),impact:`${120+i*48} hours saved`,accent:["#295b8f","#3f6d60","#8a6237"][i%3]}));

export const getSolution = (id:string) => solutions.find(s=>s.id===id);
export const searchSolutions = (query:string, filters:{category?:string; department?:string; technology?:string}={}) => {
 const terms=query.toLowerCase().split(/\s+/).filter(Boolean);
 return solutions.filter(s=> (!filters.category || s.category===filters.category) && (!filters.department || s.department===filters.department) && (!filters.technology || s.technologies.includes(filters.technology))).map(s=>({s,score:terms.reduce((n,t)=>n+((s.name+" "+s.description+" "+s.keywords.join(" ")+" "+s.technologies.join(" ")).toLowerCase().includes(t)?1:0),0)})).filter(x=>!terms.length||x.score>0).sort((a,b)=>b.score-a.score||b.s.reuseCount-a.s.reuseCount).map(x=>x.s);
};
